version: 2.1

orbs:
  maven: circleci/maven@1.1.0

parameters:
  tag:
    default: '11.0'
    type: 'string'

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
